name: CodeGuru Security Example
on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::362631904613:role/CodeGuruGitHubRole
          aws-region: us-east-2
          role-session-name: GitHubActionScript

      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: us-east-2

      - name: Print findings
        run: |
          ls -l
          cat codeguru-security-results.sarif.json

      - name: Upload result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codeguru-security-results.sarif.json
          
      - name: Trigger Enhanced Analysis Pipeline
        run: |
          aws events put-events --entries '[{
            "Source": "custom.codeguru",
            "DetailType": "CodeGuru Security Scan Complete",
            "Detail": "{\"scanName\":\"CGS-Github-CodeAnalysis\",\"state\":\"COMPLETED\"}"
          }]'
        env:
          AWS_REGION: us-east-2
          
      - name: Wait for Analysis Processing
        run: |
          echo "Waiting 30 seconds for Lambda processing..."
          sleep 30
          
      - name: Check Analysis Results
        run: |
          echo "Enhanced analysis reports should be available at:"
          echo "JSON: s3://code-analysis-results-362631904613-dev/enhanced_findings/CGS-Github-CodeAnalysis.json"
          echo "HTML: s3://code-analysis-results-362631904613-dev/enhanced_findings/CGS-Github-CodeAnalysis.html"
