name: CodeGuru Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # Optional: Run on schedule
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight

jobs:
  security-scan:
    name: CodeGuru Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required to check out code
      security-events: write  # If you plan to upload results to GitHub Security tab
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::362631904613:role/GitHubOIDCRoleCodeGuru
          aws-region: us-east-2
      
      - name: Run CodeGuru Security Scan
        run: |
          # Create a CodeGuru Security scan
          SCAN_NAME="security-scan-${GITHUB_SHA::8}"
          
          # Create the scan
          SCAN_ARN=$(aws codeguru-security create-scan \
            --name "$SCAN_NAME" \
            --analysis-type "Security" \
            --repository-source "{Branch: \"${GITHUB_REF_NAME}\", Provider: \"GitHub\", RepositoryName: \"${GITHUB_REPOSITORY}\"}" \
            --source-code-type "GitHub" \
            --query 'ScanArn' \
            --output text)
          
          echo "Scan ARN: $SCAN_ARN"
          echo "Waiting for scan to complete (this may take several minutes)..."
          
          # Wait for scan to complete
          aws codeguru-security wait scan-complete --scan-name "$SCAN_NAME"
          
          # Get scan results
          aws codeguru-security get-findings --scan-name "$SCAN_NAME" > codeguru-findings.json
          
          # Display summary of findings
          CRITICAL=$(jq '.findings[] | select(.severity=="Critical") | .id' codeguru-findings.json | wc -l)
          HIGH=$(jq '.findings[] | select(.severity=="High") | .id' codeguru-findings.json | wc -l)
          MEDIUM=$(jq '.findings[] | select(.severity=="Medium") | .id' codeguru-findings.json | wc -l)
          
          echo "CodeGuru Security Scan Results:"
          echo "Critical: $CRITICAL"
          echo "High: $HIGH"
          echo "Medium: $MEDIUM"
          
          # Optional: Convert findings to SARIF format for GitHub Security tab
          # This requires a custom conversion script or tool
          # python3 convert_to_sarif.py codeguru-findings.json > results.sarif
          
          # Optional: Fail the workflow if critical findings exist
          if [ $CRITICAL -gt 0 ]; then
            echo "Critical security findings detected!"
            exit 1
          fi
      
      # Uncomment if you've created a SARIF conversion
      # - name: Upload SARIF results
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: results.sarif
      #     category: codeguru-security
