name: CodeGuru Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    name: CodeGuru Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::362631904613:role/GitHubOIDCRoleCodeGuru
          aws-region: us-east-2
      
      - name: Run CodeGuru Security Scan
        run: |
          # Set variables
          SCAN_NAME="security-scan-${GITHUB_SHA::8}"
          RESOURCE_ID="${GITHUB_REPOSITORY}"
          
          # Create and start the scan
          echo "Creating scan with name: $SCAN_NAME and resource ID: $RESOURCE_ID"
          aws codeguru-security create-scan \
            --scan-name "$SCAN_NAME" \
            --resource-id "$RESOURCE_ID" \
            --type "Security"
          
          echo "Waiting for scan to complete..."
          
          # Check scan status
          while true; do
            STATUS=$(aws codeguru-security get-scan \
              --scan-name "$SCAN_NAME" \
              --resource-id "$RESOURCE_ID" \
              --query 'status' \
              --output text)
            
            echo "Current status: $STATUS"
            
            if [ "$STATUS" = "Completed" ]; then
              break
            elif [ "$STATUS" = "Failed" ]; then
              echo "Scan failed"
              exit 1
            fi
            
            sleep 30
          done
          
          # Get findings
          echo "Getting scan findings..."
          aws codeguru-security get-findings \
            --scan-name "$SCAN_NAME" \
            --resource-id "$RESOURCE_ID" \
            --output json > codeguru-findings.json
          
          # Display summary of findings
          CRITICAL=$(jq '.findings[] | select(.severity=="Critical") | .id' codeguru-findings.json | wc -l)
          HIGH=$(jq '.findings[] | select(.severity=="High") | .id' codeguru-findings.json | wc -l)
          MEDIUM=$(jq '.findings[] | select(.severity=="Medium") | .id' codeguru-findings.json | wc -l)
          
          echo "CodeGuru Security Scan Results:"
          echo "Critical: $CRITICAL"
          echo "High: $HIGH"
          echo "Medium: $MEDIUM"
          
          if [ $CRITICAL -gt 0 ]; then
            echo "Critical security findings detected!"
            exit 1
          fi
